### ISSUE TITLE
Txs in the block don't exist

### ISSUE THREAD

**Issue by longfin** [planetarium/NineChronicles.Snapshot#201] opened 2022-12-20 06:55 UTC
In the range 5575191 - 55760301, the transaction of the block is not included in the snapshot, so an error occurs when accessing the block.

**Comment by area363** [comment] 2022-12-21 02:38
After checking the latest snapshot files, tx data between `5575191 - 55760301` (epoch 19333, 19334) weren't missing and so the files appear to be normal.

However, I do think this problem is caused by some sort of `inconsistency in the downloading process` in which the zip files are unsuccessfully extracted, creating a missing file. I'll look more into this issue with a new update.

**Comment by area363** [comment] 2023-02-02 03:30
This issue has not occurred since merging the following PRs so I will close this issue for now.

- https://github.com/planetarium/NineChronicles.Snapshot/pull/208
- https://github.com/planetarium/NineChronicles.Snapshot/pull/209

**Closed by area363** 2023-02-02 03:30 UTC
